/* Exercise 5.23
 *
 * Text too long. Go fot it. Let's generate few hailstone numbers.
 *
 */

#include<stdio.h>
void intro(void);
void get_number(void);
void table_head(int);
void hailstone(int);

int n;


/* Main			****/

int main(){

	intro();
	get_number();
	table_head(n);
	hailstone(n);
	printf("\n\n");
	return 0;
}

/* Functions		****/

void intro(void){
	printf("\nLet's print few hailstone from a positive integer.\n"
		"Choose a number:\n\n");
}

void get_number(void){
	extern int n;
	scanf("%d", &n);
}

void table_head(int m){
	printf("\n\nHailstones generated by %d:\n", m);
}

void hailstone(int q){
	printf("\t%d", q);
	int static i = 0;
	if(++i % 5 == 0)
		printf("\n");
	if(q % 2 == 0 && q > 1)
		hailstone(q / 2);
	else if( q > 1)
		hailstone(q * 3 + 1);
}



